[tool.poetry]
name = "oceans-1876-data-pipeline"
version = "0.1.0"
description = ""
repository = "https://github.com/Oceans-1876/oceans-1876-data-pipeline"
authors = ["Kaveh Karimi-Asli <kaveh@illinois.edu>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
Pillow = "^8.2.0"
pandas = "^1.2.4"
pdf2image = "^1.15.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
ipython = "^7.24.1"
black = "^21.5b2"

[tool.isort]
profile = "black"
multi_line_output = 3
