[tool.poetry]
name = "challenger-workflows"
version = "0.1.0"
description = ""
repository = "https://github.com/Oceans-1876/challenger-workflows"
authors = ["Kaveh Karimi-Asli <kaveh@illinois.edu>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.0"
fuzzysearch = "^0.7.3"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
ipython = "^7.25.0"
black = "^21.5b2"
mypy = "^0.910"
isort = "^5.9.3"
autoflake = "^1.4"
flake8 = "^3.9.2"

[tool.isort]
profile = "black"
multi_line_output = 3
